### ISSUE TITLE
Specify which changes are allowed when a configuration profile is "actve" and save those changes to DB too

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#148]
# Description

### Context
When a Configuration Profile gets created, in the DB it only represents a single entity with all the metadata like "name" and "description" but it can still be edited to specify abstract classes, mapping predicates and all the information related to DSO's. This is because this single entity has a single attribute called `structure`, which is a JSON object  validated by this [JSON schema](https://github.com/t3-innovation-network/desm/blob/main/ns/valid.configurationProfile.schema.json).

When a Configuration Profile gets "activated", which is an option in the UI where all the configuration profiles gets listed, the structure gets parsed in a process for the creation of all the related entities to begin using it. We're talking about the following elements:

- The abstract classes with its domains
- The mapping predicates with its concepts
- The DSO's with the following related entities too:
  - The agents
  - The scheme files with the following related entities too:
    - The concept schemes with its concepts
    
 ### Core Issue
So when a Configuration Profile is activated, each change through the UI will only reflect in its structure, which is consistent when exporting it, but it's not created into the database as an entity.

### Example
Adding an agent or editing its name through the Configuration Profile edit screen will change the JSON structure, and the user will see this change both in the UI and when trying to export the CP. But the agent will not get created or edited because this process is only ran once, when the CP is activated and this is already "active".

# Taks
Need to specify what actions are allowed in these cases.

@stuartasutton @jeannekitchens

**Comment by stuartasutton** [comment]
Would changes after the configuration has been activated have to be done through the configuration profile. Could we not still use the more ad hoc processes that were developed before the notion of configuration dashboard. If no changes can be made to the abstract classes or mapping predicates after project has been activated, then all we are talking about is correcting non-substantive errors and adding DSOs and their associated entities.

**Comment by richard0000** [comment]
# Technical Proposal
- Allow changing the name of the CP
- Allow changing the description of the CP
- Block changing the mapping predicates (whole step 2)
- Block changing the abstract classes	(whole step 3)
- Permit adding new DSO’s
- Permit adding new agents
- Block removing existing DSO’s
- Permit removing existing agents
- Permit adding new schema files and linking to abstract classes
- Permit changing metadata from schema files
- Block removing existing schema files

@stuartasutton @philbarker @jeannekitchens  comments?

**Comment by philbarker** [comment]
The items in the proposal seem reasonable. I think we could live with them, but I have request to consider: for item 3, would be be possible to:
3. a. permit adding new mapping predicates to be added, 
3. b. permit changes to the label of a mapping predicate,
3. c. Block removal of existing mapping predicates.

**Comment by stuartasutton** [comment]
@philbarker, I am assuming that your 3b means maintaining the original URI while permitting changes to the label.

**Comment by philbarker** [comment]
@stuartasutton Yes, same id, different label. (e.g. label might be changed to "don't use me"!)

**Comment by richard0000** [comment]
@stuartasutton @philbarker seams reasonable.

**Comment by jbaird123** [comment]
Proposed implementation is below:

1. Allow changing the name of the CP - **Implemented**.
2. Allow changing the description of the CP - **Implemented**
3. Block changing the mapping predicates (whole step 2)  -  ** To Be Implemented (see note below)**
4. Block changing the abstract classes (whole step 3) -  ** To Be Implemented**
5. Permit adding new DSO’s - **Implemented**
6. Permit adding new agents - **Implemented**
7. Block removing existing DSO’s - ** To Be Implemented**
8. Permit removing existing agents - **Implemented**
9. Permit adding new schema files and linking to abstract classes - **Implemented**
10. Permit changing metadata from schema files - **Implemented**
11. Block removing existing schema files -  ** To Be Implemented**

Note on item 3: @philbarker had asked about adding the ability to modify predicate labels and add new predicates.  Because the current system relies only on a file upload, I recommend we defer that functionality to a later phase since the effort to implement is high and the immediate need for it is unclear.

**Comment by philbarker** [comment]
Achievable versions of points 3 & 4 will be added as new issues (enhancements)
