### ISSUE TITLE
Add Configuration Profile admin and DSO admin/s

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#149]
# Description
Once the user adds a DSO, he/she can get to the “Agents” tab and begin adding each one of the people who will be using the instance to map specifications. So each one of these users will be “mappers”.

In the wireframes, we didn’t specify a screen for adding an administrator for the DSO nor the Configuration Profile. Although we are prepared to do it, because the roles are in the platform, it will be necessary to discuss and maybe to create a basic mockup for it.

**Comment by stuartasutton** [comment]
I am not sure I understand the problem. Is it a problem in the sequencing of the actions?

**Comment by richard0000** [comment]
> I am not sure I understand the problem. Is it a problem in the sequencing of the actions?

@stuartasutton I will prepare a solution, probably a mockup, and come back to you.

**Comment by richard0000** [comment]
# Technical Proposal
- Mockup for adding Configuration Profile Admin.
- Mockup for adding DSO admin.
- Implementation  for adding Configuration Profile Admin.
- Implementation for adding DSO admin.

@stuartasutton @philbarker @jeannekitchens  comments?

**Comment by philbarker** [comment]
Proposal looks good, I think we need those mock-ups first. We need to think about how a DSO Admin gets added.

I expect a DSO admin would only have edit access on tab related to their Org in the DSO Information screen, which about hiding things rather than adding new things.

In terms of prioritization, this may be something that we could live without having for the time being. Just assume cooperative Profile Admins :)

**Comment by stuartasutton** [comment]
@richard0000, @philbarker & @jeannekitchens, I am actually questioning whether there is any need for a DSO administrator role. The information on the agents doing the mapping is gathered before entry into the configuration templates so there is no admin duties there. Obviously, there needs be an administrator of a **DESM instance**, who would have access to the configuration templates and enter the configuration data. No one else should even see the configuration option. 

So, until experience tells us otherwise, I think we need not distinguish any roles for those doing the mapping for a DSO meaning that the only other person is administrator of the DESM instance who is identified as such to the system.  In sum, we don't actually need to distinguish any roles...particularly here at the outset.

**Comment by richard0000** [comment]
@stuartasutton if your last comment is confirmed, this issue could be technically summarized for implementation as just adding a check to point out a single "Contact Agent" from the list, being the first always automatically selected.

Is this right?

**Comment by stuartasutton** [comment]
I need to revise my comment slightly. There is actually an administrative step at the completion of the DSO's mapping of an abstract class--signaling that mapping is complete. However, the solution would be the same as suggested above, with checking one of the agents of a DSO as the "Administrator/Contact" or "Lead/Contact" and then only letting that checked agent sign off when the mapping to an abstract class for the DSO is complete.

**Comment by jbaird123** [comment]
@excelsior - This was not implemented correctly.

1. Regular users should be able to click "Done Domain Mapping".  But this button has been incorrectly removed.  
2. Regular users should be able to advance to the "Alignment" screen (after domain mapping), and click "Save", but not "Done Alignment".

In summary, the only screen that should have any restrictions is the last screen.  Only "lead mappers" should be able to click "Done Alignment".  All users should be able to click "Done Domain Mapping" on the earlier screen.
