### ISSUE TITLE
Importing/Exporting a JSON-LD Mapping Export Profile

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#150]
# Description

### Mapping Export Profile
A JSON-LD mapping output file for types of a mapping or mapping sets

### Types of mapping export profiles
- A single abstract class with mapped schemas from a pair of DSOs;
- A single abstract class with mapped schemas from multiple DSOs;
- Multiple abstract classes with mapped schemas from a pair of DSOs; and
- Multiple abstract classes with mapped schemas from multiple DSOs.

# Notes
- The wireframes for phase 3, describing the Configuration Profiles Dashboard, didn't include this feature.
- We need to define the format of this JSON-LD file and take into consideration the amount of information and the significance of that information for the platform, apart from being aware of the fact that it needs to be prepared to be imported again into the platform.
- The entities involved in the process are:
  - An abstract class (a single domain? If so, we don't have a way to import a single domain ATM, we have a domain exclusively existing as part of an abstract classes set).
  - Schemas mapped to that domain, this means the following:
    - a specification to be the spine of the domain with all its terms (each term is an entity in the platform)
    - a second specification with all its terms
    - the mapping element with all its terms
    - the dso's owning the specifications (if we don't include the dso's, we can't import it later, a specification does not live in the platform without an organization)
    - if we include the DSO, we should include all its agents.
    - apart from the agents, we should include the configuration profile for the DSO? (a DSO can't be created outside from a Configuration Profile)
    - If we include the Configuration Profile, there's more...
    
 # Conclusion
 We need clarification on this topic. There's a lot of information around it and no clear way on how to process it.
 
 # Tags
 @stuartasutton @jeannekitchens @jbaird123

**Comment by richard0000** [comment]
# Proposal

## Technical design
- Add a unique URL for the DOS (as an identifier across DESM instances). So when importing a mapping profile, each schema includes a reference to it.
- If the instance has a DSO with that URL, the import can be completed, otherwise not.

## File Structure
- The export should have a structure (we should build a JSON schema for it) covering the following:
  - Abstract class URI
  - Schema, each with terms and DSO URL.
  - One mapping element for each schema.
  - All the terms of a mapping with information about the predicate, comments, etc.
  - Spine (the final specification with all the terms from the mappings).
  
## Interface
We should let the user pick a Configuration Profile from a list. This will be the environment to work on the result of the import of the mapping export profile. We will need mockups for it.

@stuartasutton @jeannekitchens @philbarker

**Comment by stuartasutton** [comment]
@richard0000  and @philbarker , we have an export schema defined for a mapping and have had for some time. Recall that it is primarily based on exporting/importing a crosswalk for a single abstract class and 1-to-n DSO mappings to that single abstract class. Now a project may have more than one abstract class and its mappings, that's what the AbstractClassSet in the top left of the following diagram captures--an aggregation of crosswalks to two or more abstract classes. 

![Domain_Model-REV-Sets](https://user-images.githubusercontent.com/2939046/144659992-e5a64ee7-cb26-49ba-ba19-bd9c88cd4533.png)

So, if a project has only one abstract class in the mapping (and I assume there will lots of those) with 1-to-n DSO's mapping to it, there would be no instance of the AbstractClassSet in the data since there is nothing to aggregate into a set.  AbstractClassSet comes into play only when a project has more than one abstract class. BUT, the basic unit of output of a crosswalk is to a single abstract class. 

If we are importing a crosswalk that has been exported, it will have to reference by URL the configuration profile output on which it was based; so, the crosswalk cannot be uploaded until the configuration profile on which it is based is also loaded.

Given my comments here, are your questions the same (meaning I missed the point)?.

**Comment by richard0000** [comment]
# Technical Proposal
- Allow referencing a CP uniquely through a URL.
- Build the JSON schema file to establish a valid structure for the mapping export profile with all the necessary information.
- Develop the export feature, meaning the translation of all the involved information into JSON.
- Build the import mockup with specifications about the “how” and options to select and input if necessary.
- Develop the import feature.

@stuartasutton @philbarker @jeannekitchens  comments?

**Comment by philbarker** [comment]
What information is needed from the Configuration Profile that isn't in the schema above?
Here's what is in the schema:

1. the information about DSOs is in desm:SDO [aside: I think DSO (Data Standard Org) makes more sense]
2. the information about their agents is in desm:Agent
3. the information about schemas is in desm:Schema [aside: I think there should be a link between desm:Schema and rdf:Property rather than rdf:Property and desm:SDO -- I think we need to know which property being mapped somes from which schema]
4. mapping predicates are one of the skos:ConceptSchemes at the top
5. absract classes are the other skos:ConceptScheme at the top

Is there anything else needed?

I think all I might add would be some graph-level metadata describing the mapping as a whole.

**Comment by stuartasutton** [comment]
@philbarker & @richard0000 as for Phil's aside in no. 3, I have updated the model and replaced the image above. In sum, a DSO `hasSchema` and `hasScheme`. A `Schema` `hasProperty` and a `Property` `inSchema`.

As for the "graph0level metadata", that should be the metadata from the configuration profile describing the mapping project.

**Comment by philbarker** [comment]
@stuartasutton In the domain model, what is the `rdfs:range` link between `rdf:Property` and `sckos:Concept` for? Maybe it should be `rdfs:domain` so that we can represent the AbstractClass at a property level (e.g. for spine terms).

**Comment by stuartasutton** [comment]
Phil, I think the `rdfs:range` link between `rdf:Property` and `skos:Concept` in the model is useful (if not necessary) where the value of the property is a particular concept in a concept scheme. I understand that the `rdfs:range` link between `rdf:Property` and `rdfs:Class` could capture it, but that could be said for any of the properties referencing `skos:Concept` and `skos:ConceptScheme`.

Or have I misunderstood you comment?

**Comment by philbarker** [comment]
OK, but why not rdfs:domain as well? For the example I made I found myself wanting to say what the abstract domain of a spine term is, but not really the range.

Perhaps we would be better to continue the discussion this under issue #160 , rather than hijacking this issue (sorry Riccardo)

**Comment by stuartasutton** [comment]
@philbarker & @richard0000, we do have a [JSON-LD schema in Github](https://github.com/t3-innovation-network/desm/blob/main/schemas/desmSchema.jsonld) as well as a [turtle version](https://github.com/t3-innovation-network/desm/blob/main/schemas/desmSchema.ttl) in the [DESM schema folder](https://github.com/t3-innovation-network/desm/tree/main/schemas) for the [domain model (updated)](https://github.com/t3-innovation-network/desm/issues/150#issuecomment-985772672) at the top of this issue. The JSON-LD version includes its context as opposed to referencing it since it is easier to keep in sync as long as the schema is unstable.

@richard0000, has asked whether #150 and #151 overlap and whether we can close #151. I think it is safe to do so.

**Comment by stuartasutton** [comment]
@philbarker, @ricardo, & @jeannekitchens, given the considerable overlap in content between the DESM configuration profile and a mapping, is there any reason to consider them as separate beasts on export or import?  Given Phil's concern about conforming to privacy regulations, we could consider exports and imports for the following two scenarios:

1. (Config Profile + Mapping(s)) + Agents
2. Config Profile + Mapping(s) 

That would mean that an export without agents would need to be importable and addition of agents permitted.

Thoughts?

**Comment by richard0000** [comment]
@stuartasutton I think we could make the export available for the mapping export profile as follows:
## Export
- The abstract class/es involved
- The mappings against it, with all the related information (***note1**)

## Import
- The user will be asked to select a configuration profile from a list of the "active" ones in that DESM instance. If no active CP found, do not permit the import.
- The abstract classes should be unique by URI in the context of a DESM instance, so it will not be created if found while importing, otherwise it will be created (added to the selected CP) in that DESM instance.

No need for more changes, the DSO's and agents will be different, meaning the ones already configured for the selected CP.

***note1**: Would need to make changes to the existing models, since some can not live without its relations, like a specification and the user who uploaded it.

Please let me know if this is fine.

@philbarker @jeannekitchens

**Comment by philbarker** [comment]
@richard0000 
I'm unsure why there should be an active config profile in order to permit import. It might be easiest to explain this during a call.

I think the Abstract Classes are just constructs used for a specific mapping, but I wonder if others see them as something more definite? For example many mappings might have an abstract class for "Person", but they needn't have the same identifier (or even know about each other). In which case the URIs for Abstract Classes could just be generated from UUIDs or similar.  But if we do want an abstract class of Person that exists in many mappings then we might need to think about how different mappings would interact.

**Comment by stuartasutton** [comment]
An abstract class of Person in many mappings would be named with the same URI otherwise it is not the same abstract class. Am I missing something?

**Comment by richard0000** [comment]
@stuartasutton here are my notes from our last meeting plus some comments as replies to the latest ones.

# Notes from the meeting
- Since the concept and concept schemes can always be referenced by URI, the mapping export profile will have a reference to a concept scheme and, we will export all the mappings related to each of the concepts found in the concept scheme.
- It's not necessary to include the configuration profile in the export, but it's required to select one from the destination DESM instance before importing (we can always export the CP too and import it first).

This means that when we are importing it, we will be able to find the JSON body of the concept scheme plus we will have in the imported JSON-LD file all the mappings to be created in the target DESM instance.

# Additional Notes
I say the configuration profile must be an "active" one, otherwise do not permit the import, because I understand that the whole purpose of importing a mapping export profile is to work on it. And in order to work on it we need to have reference to the abstract classes, which are only created when a configuration profile is activated.

## My thoughts now that I'm putting it to words, are:
- If we don't need to create the abstract classes because we only reference it, we could just keep it as reference on all the places we work with abstract classes (same for mapping predicates) and do not store it in the DESM instances. So all the DESM instances would be just referencing these entities and working with it in memory when needed.
- This change will allow in the future to not depend on things stored in any instance, but in the cloud, which can be easily replaced by a library (the product that was requested and didn't get in the current budget).

I will discuss these items with a technical partner and be back with more details but, I think I have what I need.

**Comment by philbarker** [comment]
> I say the configuration profile must be an "active" one, otherwise do not permit the import, because I understand that the whole purpose of importing a mapping export profile is to work on it. And in order to work on it we need to have reference to the abstract classes, which are only created when a configuration profile is activated.

Well, yes, but the information about the abstract classes (and mapping predicates) are in the mapping export profile, or possibly linked to by it. So, in order to be sure we have the same abstract classes and mapping predicates we need to be able to import the data about them from the profile before activation. 

Maybe the import is a two-stage thing: import data about the config before activation and data about the mapping after, but it may all be in the same file.

**Comment by stuartasutton** [comment]
Yes to "...all be in the same file"
