### ISSUE TITLE
Develop import support for existing DESM machine-encoded mapping files.

### ISSUE THREAD

**Issue by richard0000** [t3-innovation-network/desm#151]
# Description
## Goal
The goal is to add the features of:
- The addition of new specifications to that existing mapping, and
- Making necessary edits and updates to that existing mapping.

### The export file
We have modeled the export of a mapping in the requested format for the previous phase. This format does not include all the necessary information to import it again. We will need to include now:
- the DSO's
- all the necessary information related to those DSO's
- As a DSO does not exist outside a configuration profile currently, we may need to define whether we include this too (which will imply including all the information related to it) or do the import inside a configuration profile (or discuss another possible approach). 

### The mapping model
We don't allow a mapping to have more than 2 specifications involved (see [this diagram](https://miro.com/app/board/o9J_l29jAjw=/?moveToWidget=3074457362476923040&cot=14)). We will need to define all the architecture changes around this feature to support it.

**Comment by stuartasutton** [comment]
As for export of a mapping file, we need to be clear that there are three distinct uses of a mapping files after export: 

1. viewing in a 4rd party viewer where all of the details of the configuration profile (CP) used to generate it need not be present; 
2. when the exported mapping file needs to be brought back into an instance of the DESM tools for updating.

Since the 2nd use cannot happen except in conjunction with a matching CP, at a minimum, the mapping file should identify by URI the CP used in its creation. I don't know whether that means that they should be combined into a single JSON-LD file or related by reference.

**Comment by richard0000** [comment]
# Technical Proposal
- Mockup for the import interface.
- Definition of all the related data (Configuration Profile, DSO, ...) 
- Build the UI with all the necessary options and message to the user on the “how” (a CP will be necessary, so this will be necessarily present, meaning created or imported before)
- Develop the import logic (create all the instances in DB)

@stuartasutton @philbarker @jeannekitchens  comments?

**Comment by philbarker** [comment]
This is a complex task. We have a schema (or at least the [design of a schema](https://github.com/t3-innovation-network/desm/issues/150#issuecomment-985772672)) for how mappings are represented, but we need to think hard about how to map the data stored to this schema, and how the data would be used once exported. I think we will see more concrete issues and proposed resolutions emerge when we do that.

**Comment by stuartasutton** [comment]
Closing since overlaps with #150.
