### ISSUE TITLE
Integrating configuration and mapping models.

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#166]
@philbarker & @richard0000, in this issue, I am proposing a small but very significant change in the domain model in order to integrate the configuration and mapping models into one model.  This builds on the model as presented in https://github.com/t3-innovation-network/desm/issues/150#issuecomment-985772672 containing Phil's example.  The revised model is below. The changes are in red:

![Domain_Model-REV-Domain Model-Rev drawio](https://user-images.githubusercontent.com/2939046/147000328-d9e90868-798d-4b95-b65f-d0163e4afce7.png)

The red bordered class used to be the desm:AbstractClassSet and is now the proposed desm:MappingConfiguration. The properties already on that class align perfectly with the wireframe for "General Data about the Configuration Profile".  The change adds one property--desm:hasDSO--to link the desm:MappingConfiguration to two or more DSOs which then link to schemes and schema etc.

Thoughts?

**Comment by philbarker** [comment]
I think those changes make sense 

The hasPart/isPartOf relationships between MappingConfiguration and AbstractClassMapping looks a little odd now that the MappingConfiguration is not explicitly a set, because in a sense everything in the conifguration is a part of the configuration. I could live with that -- especially as my first thought for changing it had me questioning the relatinships between AbstractClassMapping and TermMapping and Property to TermMapping.

**Comment by stuartasutton** [comment]
Phil, the AbstractClassMapping is the mapping for a single abstract class. Mappings of multiple AbstractClassMapping is handled through the hasPart.

**Comment by jbaird123** [comment]
@excelsior - This is part of the requirement for the configuration profile import / export feature.

**Comment by jeannekitchens** [comment]
@jbaird123 is this implemented? In progress?

**Comment by jbaird123** [comment]
@jeannekitchens - This is a question for @philbarker to answer after he's had a chance to verify the exports.  Why did you add the blocker label?

**Comment by philbarker** [comment]
See issue #445 for continuation of this.
