### ISSUE TITLE
Update DESM Landing Page

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#311]
**DESM is designed to make mapping easy and support the currency of mappings over time.  It supports pairwise, semantic mapping of schema terms and their definitions using a synthetic spine agnostic to data models and formats.  

Resultant mappings are intended to help data standards organizations, developers, decision makers, and others have a clear understanding of how schemas map and provide useful visual and data outputs of completed mappings. **

Link instructions for mappers.
Provide instructions for seeing mappings.

**Comment by philbarker** [comment]
(First draft)

## About the DESM tool
The Data Ecosystem Mapping Tool (DESM) is a specialized tool for creating, editing, maintaining and viewing crosswalks between data standards from two or more Data Standard Organizations (DSOs). These crosswalks are based on the degree of semantic alignment between terms in the different standards or schemas, and may be useful for:

- supporting translation of data from one standard to another, 
- supporting the development of data models that align to several standards 
- showing which standards cover what terms,

among other uses. These uses recognize the reality that any data ecosystem will encompass actors who use different data standards, different models and different schemas, because they have different interests, systems and requirements for the data. Data translation allows a degree of interoperability despite the use of data standards; however our ultimate hope is that semantic mapping will show that data harmonization is possible, that is that different data standards can share semantics and models for common elements.

The crosswalks are based on pairwise mapping of terms from the different standards to a "synthetic spine", a schema-neutral synthesis terms that is created during the mapping. Mappings from terms in one standard to terms in another can then be inferred where their respective mappings to the spine are transitive.

The [DESM tool is available](https://github.com/t3-innovation-network/desm) as Open Source Software under an Apache 2.0 license. 

[Instructions for setting up an instance](https://github.com/t3-innovation-network/desm/blob/main/README.md) of the DESM tool are available from the repository.

[Instructions for carrying out a mapping](https://github.com/t3-innovation-network/desm/wiki) are available on the DESM repository wiki.

## Acknowledgements
[TBD]

**Comment by philbarker** [comment]
OK [that's](https://github.com/t3-innovation-network/desm/issues/311#issuecomment-1278845345) my starter for text to show on the home page of a DESM instance. This text makes sense as a shared, generic description of DESM, however it strikes me that there will be information that needs to be added on an instance by instance basis, e.g what is being mapped in a specific instance, who is responsible for it, how do people get access to that instance; and also that some of the generic information might not be wanted, but there might be some text (aknowledgements etc) that we want kept.

**Comment by jeannekitchens** [comment]
@jbaird123 in addition to Phil's write up above.  Include the following:

DESM is sponsored by the U.S. Chamber of Commerce Foundations' T3 Innovation Network program.  The T3 Open Competency Network, in partnership with the T3 Data and Technology Standards Network is responsible for the requirements and project plans that are used for development and enhancement of the DESM too. 

If you are interested in participating with a T3 mapping project, please contact Taylor Hanson thansen@uschamber.com.

**Comment by jeannekitchens** [comment]
On the left side of the landing page the following text should also be updated or removed:
Map your specification to a base schema

1. Upload Your Specification
2. Coarse Grain Mapping
3. Fine Grain Mapping and Tuning
4. Download Mapping

Either remove it altogether or change it to something like this.

Map your schema:
1. Upload your schema
2. Map the schema's properties and concepts
3. Review and download the completed mappings

**Comment by jbaird123** [comment]
@jeannekitchens @philbarker @dmsaunders: Please review the changes that we made based on your notes above.  If there are additional changes needed, please provide exact text and detailed descriptions needed (to eliminate any guess work).

**Comment by philbarker** [comment]
@jeannekitchens @DMSaunders do we need the image? I'm not sure it explains much.

**Comment by jeannekitchens** [comment]
No.  Not at this time.  The pilot may help us create an image.  The only
one I can think of that might be useful is in our deck as a backup showing
the synthetic spine but I think it has to be updated.

Jeanne Kitchens
Chief Technology Services Officer
Credential Engine
217.494.6558
***@***.***


www.credentialengine.org
www.credreg.net

*Credential Engine is a non-profit whose mission is to map the credential
landscape with clear and consistent information, fueling the creation of
resources that empower people to find the pathways that are best for them.*

**Comment by jbaird123** [comment]
Resolved.
