### ISSUE TITLE
Discourage password managers from targeting any fields that they don't belong in

### ISSUE THREAD

**Issue by DMSaunders** [t3-innovation-network/desm#332]
For example, we found the field for name for a mapping gets the attention of a password manager. Worth seeing if this affects anything else. This is not high priority.

**Comment by jeannekitchens** [comment]
@philbarker this issue was brought up by your use of a password manager tool. If role managment is enhanced so not to require multiple logins with different passwords, it should take care of this.  It seems correct for a password manager to identify with the password entry.  If you concur that the enhancement to fix the problem of multiple passwords takes care of the issue, I'm going to close this since we already have that issue on the list.

**Comment by philbarker** [comment]
@jeannekitchens the white and teal logo on the right of the specification name field is the indicator that my password manager thinks this field is one which contains sensitive/personal information. 
![image](https://user-images.githubusercontent.com/658047/221355737-9211d2b6-8380-42de-8687-f56223df3e0b.png)

This is nothing to do having many usernames and passwords. 

I suspect the field is called "name", and I suspect that if it were called "SchemaName" there would be no problem.

It's a minor issue, but possibly with a trivial solution.

**Comment by philbarker** [comment]
Probably just my password manager at fault.
