### ISSUE TITLE
No properties found when uploading json-schema

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#357]
When uploading the JSON-Schema file for A4L SIF, all is well until you see what is found in the imported file:

![image](https://user-images.githubusercontent.com/658047/205289971-f45f3c4d-8a3c-4136-b12e-f18984a1046e.png)

There is a copy of the file at https://drive.google.com/file/d/1yMkcdRg1fGLb105lEYiHsG9wFXkQEDGV/view?usp=share_link 

@excelsior what does the code look for in JSON Schema order to identify Classes and properties?

**Comment by philbarker** [comment]
tagging @4pins for info

**Comment by jeannekitchens** [comment]
@jbaird123 I'm tagging this one as blocker as well. Above is a link to the A4L JSON file.

**Comment by excelsior** [comment]
@philbarker There are two problem with the imported file.

First of all, JSON Schema uploads are expected to be uploaded in the form of a ZIP archive. Otherwise, they are treated as JSON-LD or RDF/JSON uploads.

I tried archiving and uploading the file. However, the schema itself appears to be invalid. The [validator](https://www.jsonschemavalidator.net) returns the following error:

```
Unexpected token encountered when reading value for 'value'. Expected StartObject, Boolean, got StartArray. Path 'definitions.AddressSubregion.properties.value', line 28079, position 18.
```

And there are dozens of errors like the above.

**Comment by 4pins** [comment]
Wow.  This week we just had feedback about JSON issues from New South Wales in AU, now this.  We have an Australian working on fixes.  Thanks for pointing this out.

+1 On upload clarity.
