### ISSUE TITLE
Incorrect mapping for synthetic properties

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#397]
Having used CTDL to initiate the spine, and added a property from schema.org to the spine, on completion of mapping the property added from schema.org shows as a CTDL property:
![image](https://user-images.githubusercontent.com/658047/211299846-5da597c4-7bbf-4c62-b202-0d71f9be970f.png)

Note that postalCodeBegin is not a property in CTDL. [edit: nor is postCodeEnd

**Comment by excelsior** [comment]
@philbarker I couldn't reproduce this problem. Could you instruct me on which server and under which configuration profile I will find the above mapping, so I can inspect it?

**Comment by philbarker** [comment]
I think that specific instance maybe got deleted by accident -- it's on the text project that we were using to verify that adding and deleting properties during a mapping would work.

I've added it back, see https://tool.desmsolutions.org/mappings-list?abstractClass=Organization

**Comment by excelsior** [comment]
Thanks Phil, but I stiil see neither `postalCodeBegin` nor `postalCodeEnd` properties on that page.

**Comment by philbarker** [comment]
Oh. I do, right at the bottom. I click the link above. I get asked to Choose Configuration Profile and select "Pilot Profile for Testing Completed Github Issues" At the bottom I see
![image](https://user-images.githubusercontent.com/658047/216323246-4d8e5e2e-4846-4488-b15f-4eeae2e4c555.png)

That's showing schema:postalCode**Begin** mapped as identical to postalCode**End** from Credential Engine, which is messed up in all sorts of ways given all I did was add the first as a synthetic element.

**Comment by philbarker** [comment]
Aside: is there any way to link to a view of a specific mapping without being asked to Choose Configuration Profile after clicking the link?

**Comment by philbarker** [comment]
May be related to issue #415

**Comment by DMSaunders** [comment]
<img width="1117" alt="Screen Shot 2023-02-02 at 9 34 35 AM" src="https://user-images.githubusercontent.com/37890092/216399512-2b39db98-3caf-41ee-ae08-6237a91a5a81.png">

We observed that PESC was the last to map, so they should not have any terms mapped to anything they added to the spine expect PESC terms. 
1. we need to verify that PESC did add "name prefix" to the spine
2. and see what's mapped to it - should be nothing except for PESC

**Comment by DMSaunders** [comment]
We also note that CEDS does not have an element for Deceased Indicator. It is an option that affects an element but not an element and should not appear as a term here.

**Comment by excelsior** [comment]
> Aside: is there any way to link to a view of a specific mapping without being asked to Choose Configuration Profile after clicking the link?

Unfortunately, there is no such way yet. And was looking at the wrong profile, that's why I couldn't find the property in question.

**Comment by excelsior** [comment]
@philbarker What's the correct way of fixing this issue? Should we not display synthetic properties on the Shared Mappings page or should they be marked somehow?

**Comment by philbarker** [comment]
@excelsior the problem is that mappings shown for the synthetic properties are wrong. We think some of them cannot have been entered by the user, because as Danielle points out the spine property was not there when the mapping was done. Also the initial example cannot have been added by any user because the mapped property from Credential Engine does not exist.

Can you verify that the mappings are actually in the system? Is the back-end data getting corrupted?

**Comment by excelsior** [comment]
@philbarker Well, yes, they are in the system.

When a synthetic term gets added to a spine, we generate empty mappings for that term for each of the spine's previously uploaded specs. That's because the data model requires them to be present. And I do see some of those auto-generated synthetic mappings still remaining empty, meaning that the users didn't drop anything onto them.

However, the ones that aren't empty don't look good to me, they indeed appear to be corrupted. All of those were added awhile ago, and our logs get truncated, so unfortunately I can't tell whether they were added by the users or elsehow.

I suggest removing the corrupted ones and continuing the investigation once a new one emerges.

**Comment by philbarker** [comment]
OK, thanks for info @excelsior 
I'm changing the tag for this to "Property mapping" rather than "Viewing mapping" as it seems that is where the error is.
I'm adding a "need further information" tag so that we do more investigation of what happens when terms are added / removed from the spine.
@jbaird123 @jeannekitchens if we do confirm that mappings are getting corrupted in the back end through legitimate operations, that is obviously a big problem.

**Comment by philbarker** [comment]
I have successfully messed up another mapping. This time I have [a recording](https://drive.google.com/file/d/1pcXqJcDs-ojY1EuT7XgT6inH8Xu5seWE/view?usp=share_link) of what lead up to it.

The mapping is the Course mapping in the "pilot profile for testing github issues" ([here](https://tool.desmsolutions.org/mappings/60/align), maybe, if the link works) Abstract is mapped as identical to Audience.

The recording shows what lead up to this:
0:00 to 01:14  Login, start new mapping for Course choose the schema.org schema file and upload, imports OK, select Course class in the schema schema, 6 properties uploaded. Add 5 of them for mapping and save.
A new spine was created. Logout.
Realise that there are properties in other schema.org classes that can be used when describing a Course.
01:15 to 02:17  Log back in  and mark the mapping back to uploaded, resume mapping and see that there is no way to add properties that were not initially uploaded. Add the one property (courseInstance) that wasn't added before form the 6 that were uploaded. Save changes.
A new spine was created. No further mapping is necessary
02:17 to 02:39  Spine mappings look OK, but it only shows the original 5 properties, I don't see courseInstance.
02:39 to 04:20  Ponder a while, view all mappings, put mapping back to uploaded, see that Course has 6 properties uploaded. Ponder some more 
Decide to upload some more of the properties that I need, but as a new mapping.
04:20 to 05:52 Start new mapping, upload schems schema select CreativeWork class 111 propertries found, I select five, save.
05:53 - 06:20  courseInstance is still not showing
06:20 - 06:57  Add new terms as synthetic properties & save
Changes saved
06:57 - resume mapping  on original terms, not entirely sure what the first screen  shows, but next screen when you first see wrong mappings, e.g. abstract to dateCreated; Go out and back in and abstract is now mapped to audience.

**Comment by jbaird123** [comment]
@philbarker - Thanks.  This is great!  I have been able to simplify the process of creating the error and will be posting a condensed video shortly.

Please note that there is no issue at the place where you stated: 

> 02:17 to 02:39 Spine mappings look OK, but it only shows the original 5 properties, I don't see courseInstance.

The reason you don't see that property in the spine is because you never added it to the spine as a synthetic element.  You added it to the list of properties in the Domain Mapping step, but after that you need to add it as a synthetic element.  I'm sure you were confused because there is another issue I noticed.  When you clicked "Done Domain Mapping" after adding the courseinstance property, the message "A new spine was created." was displayed in green which probably made you think that the courseinstance property had been added to the spine.  This, however, is not accurate.  That message should not have been displayed (because the spine had already been created).  I created Issue https://github.com/t3-innovation-network/desm/issues/430 to deal with that problem.

So while you did notice that courseInstance was not in the spine, that is in fact not an issue and has nothing to do with this ticket.

As I said, your video was helpful though in showing how to reproduce the issue, and I'll be adding further detail here for @excelsior soon.

**Comment by jbaird123** [comment]
@excelsior @philbarker - Here is a more detailed video which shows the issue with greater clarity.  Make sure you have your speakers on because there is audio associated with this video.  https://share.vidyard.com/watch/WAXo98d66eyoWzM25xBfa3?

**Comment by philbarker** [comment]
Thanks for getting to the root of the issue Joe.

**Comment by excelsior** [comment]
@philbarker @jbaird123 Thank you both for the videos, those were immensely helpful in identifying the root cause. 

I deployed the fix.
