### ISSUE TITLE
Provide a CSV as an option for downloading a mapping

### ISSUE THREAD

**Issue by jeannekitchens** [t3-innovation-network/desm#398]
Based on mapping filtering download a CSV including one or more pairwise mapping.  This Credential Engine page was used by the DESM designer to inform the UI for viewing mappings and should include a CSV download option https://credreg.net/page/t3mapping.  Credential Engine has since hid the CSV download to the mappings no longer being entirely accurate.  I will attach the CSV that has since been hidden from the T3 mapping page.

**Comment by philbarker** [comment]
We will need separate CSVs for each mapped schema. The name of the CSV should have metadata of DSO name and Schema name + version.

The columns in the CSV should be:
* Spine term name
* Spine term definition
* Spine term class/type
* Spine term organization+schema
* Mapping predicate label
* Mapping predicate defintion
* Mapped term name
* mapped term definition
* mapped term class type
* comments
* transformation notes

**Comment by philbarker** [comment]
Implement [as above](https://github.com/t3-innovation-network/desm/issues/398#issuecomment-1787089691) for starters,  and provide download option on visible pages per issue #424

**Comment by philbarker** [comment]
@excelsior  When I look at a mapping in DESM, e.g. the vocab mapping demo, the value for "Class/Type" is the domain of a property, or class to which the property belongs

![Image](https://github.com/t3-innovation-network/desm/assets/658047/459891ce-588b-437b-98f0-a8998d148bfd)

But in the CSV download the column Spine term class/type has the range or expected datatype of the value of the property:
 Spine term class/type
rdf:langString
rdf:langString
ceterms:CredentialAlignmentObject
ceterms:CredentialAlignmentObject

Both are useful, but we should be consistent, and currently that means display the domain.

Moving back to "in progress"

[Aside: I will check whether there is an issue about displaying the range/expected value type.]

**Comment by philbarker** [comment]
@excelsior thank you, that is exactly what we asked for....

Unfortunately since we asked we have acted on the issue of "Organization" not being quite what we planned it to be, so the column with "Spine term organization+schema" needs to be changed in accordance.

Also, there should be something in the table about the origin of the terms being mapped. My error in missing that, sorry! It won't be enough that it is in the file name once the tables for different mappings get merged.

So please can we make these changes
- [ ] Change "Spine term organization and schema" to "Spine term origin" which should have the schema name and version from which the term was added to the spine.
- [ ] Add a column "Mapped term origin" which should be the schema name and version for the term being mapped.

**Comment by philbarker** [comment]
Looks good now. Thank you.

**Comment by AH1CEDS** [comment]
@edgarf , The CSV files can be downloaded for each mapped schema and have the correct column names as well as file names. 

However, the CSV files for the tests I ran appear to have incomplete info (the CSV file shows only the spine term but not the mapped term(s)). Also, depending on the download method, there were differences in (a) which CSV files were being exported (just the pairwise mapping vs. the zip with the mapping+the spine) and (b) the values in the “mapped term definitions” column. See **Public facing mapping download functionality** issue #424 for more details, including screenshots.

**Comment by dlawsonQIP** [comment]
Verified CSV download on gopher staging.

**Comment by philbarker** [comment]
The download functionality seems to work on Cred Eng. Issues with what is downloaded notwithstanding (I have #573 for the rdf download, and #424 for the CSV) I think we can call this one done.
