### ISSUE TITLE
Add new mapping predicates (and maybe edit existing ones) even though mapping has started

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#400]
Sometimes it becomes clear that you don't have the right mapping predicates only when you have set up a project and started mapping.

Realising that it can affect existing mappings, it should still be possible to add new mapping predicates while a mapping project is in progress. 

Realising that it can be dangerous, it should maybe possible to edit some aspects of a mapping predicate in use in a mapping project. For example to change a label or description without changing the intended meaning and so leave mappings that use that predicate, or to make changes to the meaning of a predicate with the option of deleting mappings that use that predicate.

Hopefully the need for this will decrease as we get more experience with mappings and can move people towards a standard set of mapping predicates.

**Comment by edgarf** [comment]
@philbarker do we really need to do anything here? @shlag3n implemented ability to update predicates back in this task https://github.com/t3-innovation-network/desm/issues/450

**Comment by philbarker** [comment]
@edgarf What's the process for doing this? (sorry I missed your earlier question)

**Comment by shlag3n** [comment]
@philbarker re error you've got - it's because that skos file contains [2 predicates with the same prefLabel](https://github.com/t3-innovation-network/desm/blob/main/samples/mappingPredicates/pilotMappingPredicates_2.ttl#L32-L38) and we have uniqueness constraint on that. I know that it's not a workable solution, but just in case, I added a more meaningful message that includes the value causing the validation error.

**Comment by philbarker** [comment]
@shlag3n yes, more meaningful messages are always good.  It's probably not a good idea to have two predicates with the same prefLabel :-}.
