### ISSUE TITLE
Cannot download other people's mapping

### ISSUE THREAD

**Issue by philbarker** [t3-innovation-network/desm#412]
Logged in to my schema.org alias mapping account I can only download my own mapping, not other people's mappings, even though they are completed I see the download icon by them, clicking that icon does nothing.

**Comment by excelsior** [comment]
Only users from the same organization were able to download mappings. I enabled mapping export within the given configuration profile.

**Comment by jeannekitchens** [comment]
@excelsior @jbaird123 once mapping are completed anyone should be able to access and download them.  The tool is meant to provide the UI and the downloads to people who do not have to authenticate to see or download completed mappings.

**Comment by jbaird123** [comment]
@jeannekitchens - This would actually be a design change as the page we're working on is visible only to authenticated users.  In order to accommodate your request, we will need to find a way to add a download feature to one of the other pages that does not require authentication.  Since that was never included in any mockups, I don't know of any straightforward way to add it.  We can certainly do this, but I think it should be done as a separate enhancement issue.
