### ISSUE TITLE
Public facing mapping download functionality

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#424]
Need to add new functionality to allow public users to download mappings.  This currently only exists for authenticated users, and a new screen may need to be mocked up for it.

**Comment by philbarker** [comment]
The turtle export looks all wrong, just a load of disconnected BNodes with no namespace prefixes declared.  e.g.:
```
 [
    <dct:creator> [];
    <dct:isPartOf> [];
    <desm:AbstractClass> [];
    <desm:hasProperty> [];
    <desm:homepage> [];
    <desm:inTermMapping> [];
    <desm:isClassMappingOf> [];
    <desm:mapper> [];
    <desm:mappingPredicateType> [];
    <skos:inScheme> []
  ] .

 [
    <dcterms:created> "2024-07-04";
    <dcterms:dateModified> "2024-07-08";
    <dcterms:hasPart> [], [], [], [], [], [], [];
    <dcterms:title> "Phil SDO - PJJK - Organization";
    <desm:abstractClassMapped> []
  ] .

...etc
```

I see at least one problem in the JSON-LD you have :

```
"rdfs:domain": [
                {
                    "@id": "ceterms:CredentialOrganization"
                },
                {
                    "@id": "ceterms:Organization"
                },
                {
                    "@id": "ceterms:QACredentialOrganization"
                }
            ],
            "rdfs:range": [
                {
                    "@id": "ceterms:CredentialPerson"
                }
            ]
        },
```
but there is no namespace entry for the prefix ceterms: in the context so you are setting `@id` to a string. Best use the full IRIs.

Also, rdfs:range and rdfs:domain have semantics don't work the way we want (especially for non-rdf terms). Probably best to have our own properties desm:rangeIncludes and desm:domainIncludes

**Comment by AH1CEDS** [comment]
@edgarf , I tested downloading the same new mapping I created on July 12, 2024 ([DESM - Shared mappings (desmsolutions.org)](https://tool.desmsolutions.org/mappings-list?abstractClass=Person&cp=19)) in 3 formats (TTL, JSON-LD, and CSV) as 

a)	a different authenticated user that is accessing the mapping using the download icons (screenshot1), and 
b)	an anonymous user that is accessing the mapping using the direct link and a drop-down menu (screenshot2).


**Screenshot1**
 
![image](https://github.com/user-attachments/assets/a7d20986-9227-4e4a-ba6f-625331e9bfc9)

**Screenshot2**

![image](https://github.com/user-attachments/assets/b18d5998-d53c-4cec-93ea-dc01bc2afd8a)

In both cases, I was able to download files in all formats. However, 

1. the JSON-LD and CSV files appear to have incomplete info. And 
2. there were differences in how/which CSV files were downloaded depending on the download method. Specifically:

**(1)**	
**_JSON-LD:_** Some IRIs use prefixes that are not defined in the [at]context (e.g., "schema:name" and "schema:givenName") and/or appear to be incomplete (e.g., "[at]id":":P600538"). 

**_CSV:_** The file includes columns for spine terms and their mappings but many fields appear to be missing. For ex., CEDS term “name” in Person spine was “transform-mapped” to 5 properties in Schema.org. The CSV file shows only the spine term but not the mapped terms (“Has Person Name,"",""”) whereas the TTL file shows complete info including the spine term and the mapped terms.

**(2)**	 When the CSV file is downloaded using the icon (screenshot1), only one file is generated (the selected mapping only). When the CSV file is downloaded using the “Export mappings from domains” drop-down menu (screenshot2), both the spine and the mapping are exported as a zip folder with 2 CSV files. For the JSON-LD and TTL files, only the mapping is exported regardless of the download method used. Additionally, the CSV file with the mapping exported via either method has the same file name, but the “mapped term definitions” are different (see screenshots3-4).

**Screenshot3 (downloaded via icon click)**

![image](https://github.com/user-attachments/assets/fd2e4a1f-a4fa-449e-9a8c-c44ed3db02bc)

**Screenshot4 (downloaded via dropdown menu)**

![image](https://github.com/user-attachments/assets/27c36585-b15d-4a0b-970e-da12158acf7e)

**Comment by excelsior** [comment]
@AH1CEDS, 

### (1)

I downloaded the `Person` class in the JSON-LD format, and its `@context` has a definition for the `schema` namespace. 

Here's the full thing:

```json
"@context": {
    "asn": "http://purl.org/ASN/schema/core/",
    "ceasn": "https://purl.org/ctdlasn/terms/",
    "ceds": "http://desmsolutions.org/ns/ceds/",
    "ceterms": "https://purl.org/ctdl/terms/",
    "credReg": "http://desmsolutions.org/ns/credReg/",
    "dc": "http://purl.org/dc/elements/1.1/",
    "dct": "http://purl.org/dc/terms/",
    "dcterms": "http://purl.org/dc/terms/",
    "desm": "http://desmsolutions.org/ns/",
    "foaf": "http://xmlns.com/foaf/0.1/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "qdata": "https://credreg.net/qdata/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "https://schema.org/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "sdo": "http://schema.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "desm:inTermMapping": {
      "@type": "@id"
    },
    "desm:mapper": {
      "@type": "@id"
    },
    "desm:isClassMappingOf": {
      "@type": "@id"
    },
    "desm:mappingPredicateType": {
      "@type": "@id"
    },
    "skos:inScheme": {
      "@type": "@id"
    },
    "dct:isPartOf": {
      "@type": "@id"
    },
    "desm:AbstractClass": {
      "@type": "@id"
    },
    "desm:hasProperty": {
      "@type": "@id"
    },
    "dct:creator": {
      "@type": "@id"
    },
    "desm:homepage": {
      "@type": "@id"
    }
  }
```

Does it look differently for you?

### (2)

I fixed the CSV download, it includes all the mapped terms now: [Person.zip](https://github.com/user-attachments/files/16255958/Person.zip)

CSV downloads for single mappings and entire classes look differently by design (see [this](https://github.com/t3-innovation-network/desm/issues/424#issuecomment-2082360991) comment by Phil).

As for domains prefixed by colons, I think the CEDS files get processed incorrectly. Could you please share the CSV you uploaded so I can investigate?

**Comment by AH1CEDS** [comment]
@excelsior ,

- I double checked and the _schema_ namespace is indeed defined in the JSON-LD file – my apologies! We are good here. 

- The updated Person.zip CSV download you shared looks good. Also, thanks for the clarification that CSV downloads for single mappings and entire classes look differently by design. I will plan on adding this clarification to the documentation. 

- Re “domains prefixed by colons” – In JSON-LD file from 07-12-24, there are incomplete IRIs that appear to be missing a prefix, such as "[at]id": ":P600538" – these look to be associated with CEDS (so it should say "[at]id": "ceds:P600538" ?). I attached a zip with all 3 files I downloaded on 7-12, please let me know if you’d like any additional files. 

[DESM+documentation+and+demo_Person_Schema.org_2024.05.20-https_20240712182157.zip](https://github.com/user-attachments/files/16257256/DESM%2Bdocumentation%2Band%2Bdemo_Person_Schema.org_2024.05.20-https_20240712182157.zip)

**Comment by excelsior** [comment]
@AH1CEDS,

I'm afraid I wasn't clear enough. I need the original CEDS files you uploaded in order to create the mapping. Could you please share those?

**Comment by AH1CEDS** [comment]
@excelsior ,

Goit it. Phil provided the CEDS ttl file for the testing / demo purposes in [this folder](https://drive.google.com/drive/folders/16x8Uz7UmqEPaENCUoK05FhUrz0OhoZil). I cannot attach a ttl file here, so here is a txt version of it. I can convert the ttl to the CSV with a script, let me know.
[CEDS-Ontology-V12.1.0.0-noVocabs.ttl.txt](https://github.com/user-attachments/files/16265612/CEDS-Ontology-V12.1.0.0-noVocabs.ttl.txt)

**Comment by excelsior** [comment]
@AH1CEDS @edgarf  @philbarker ,

There's a problem with the way URIs with a default namespace get expanded. That's why the properties created from the CEDS data attached above lack a namespace and begin with the colon.

This has nothing to do with the download mechanism, it's an upload problem. I suggested opening a separate issue for it.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior please move the public download forward as planned. It needs to be on CE environment preferably by Monday.  The demo we've been planning for quite a while needs to include the download.  If this is a conflated issue that needs another GitHub issue, please create it.

**Comment by edgarf** [comment]
Added task here - https://github.com/t3-innovation-network/desm/issues/569

**Comment by dlawsonQIP** [comment]
Verified ability to download a mapping from Gopher staging.
