### ISSUE TITLE
Add_user wiki missing

### ISSUE THREAD

**Issue by Norlock** [t3-innovation-network/desm#486]
The following wiki page is missing: https://github.com/t3-innovation-network/desm/wiki/Adding-a-user

It has been referred to here: https://github.com/t3-innovation-network/desm/wiki/1-Logging-In.

How can I add a user on my docker environment? I need this to create a format

**Comment by philbarker** [comment]
@Norlock do you have an admin account so that you can access the dashboard and set up mapping projects? If so then the wiki page has moved to https://github.com/t3-innovation-network/desm/wiki/Configuration-Profile -- the adding users referred in the page you're on is the second part of step 4 on that.  If not perhaps @edgarf can help

**Comment by jeannekitchens** [comment]
Hello @Norlock are you affiliated with a specific project?  We're curious about what your using DESM for.  Thanks in advance for sharing this information.
