### ISSUE TITLE
"View Mappings" clarification

### ISSUE THREAD

**Issue by stuartasutton** [t3-innovation-network/desm#59]
Ricardo, just to make sure we are on the same page about a few of the data points on the "View" (see circled areas on image below).  There is a potential for user confusion between the label "Origin" in the spine column and "Organization in the mapped property column. I think both labels should be "Organization"--e.g., "PESC", "IMS Global", "Credential Engine", "D2L" etc.

The "Schema" in both columns should be the actual name of the schema file as exported by the standards body and ingested into the OCFC tool--e.g., for PESC the schema might be its Acadenic_Record_v1.13.xml or its Core_Main_v1.19.xml.  

![image](https://user-images.githubusercontent.com/2939046/100461659-f686b280-307d-11eb-8bee-253e5453f0d6.png)

**Comment by richard0000** [comment]
Got it @stuartasutton .

So the changes would be:
**a-** In the spine property column, change the label name "Origin" to "Organization", and
**b-** In the property mapping row, show the original file name (from upload phase) on "Schema".

Item **b-** would actually imply saving the file name (since we don't do that ATM).

**Comment by stuartasutton** [comment]
Yes, your interpretation is what I meant.

**Comment by richard0000** [comment]
@stuartasutton what would be the "original file name" to put on schema (item **-b**), if the user uploads more than 1 file?

**Comment by stuartasutton** [comment]
If there are two files uploaded, and the same property is used in both, then list both schema names. If the property appears in just one of the two or more files uploaded, then just list rthe file in which it appears.

**Comment by richard0000** [comment]
@stuartasutton ATM we merge the files to deal with all the nodes together. You can see the diagram [here](https://miro.com/app/board/o9J_kna9728=/?moveToWidget=3074457349661692411&cot=14). So we identify the properties after merging, not before and that's the reason we don't have a way of knowing the name of the file at that point.

### Outcome:
- In order to accomplish having the name of the file when properties are being analyzed and created, it's necessary to change the process in the diagram and that's not going to be an easy task.

**Proposal 1:**
- For uploads of only 1 file, keep the name of the single file uploaded.
- For uploads of more than 1 file, the user can point the file to reference as schema by making the file properties boxes selectable (make the 1st selected by default)

**Proposal 3:**
- Avoid having a reference for the scheme in the upload specification form.
- Once the properties are created, place the scheme attribute in it as the name of the first file uploaded.
- In the edit property modal window, add an input text box to change it.

**Proposal 3:**
- Add an input text box in the upload specification form to prompt the user to place the name to keep track in properties (fill it by default with the name of the first uploaded file).
- This will show the same name for all properties.

### Preferred option:
- Proposal 2.

Please let me know your thought. I may be missing something.

@jbaird123 FYI.

**Comment by stuartasutton** [comment]
I agree, option 2

**Comment by richard0000** [comment]
Covered in PR #70
