### ISSUE TITLE
Upload a specification requirements

### ISSUE THREAD

**Issue by jbaird123** [t3-innovation-network/desm#9]
@stuartasutton - 

Please clarify the following related tot his screen:  https://marvelapp.com/prototype/adf7283/screen/68443837?

1. "What specification would you like to map to?" dropdown represents organizations - correct?
2. Where do we specify what domain this specification is? (When I upload a specification, don't I need to specify whether I'm uploading a person, or some other entity?  I don't see this included on the mockup.)
3. What is a "Use case"? We need a list of values for that dropdown.

**Comment by jeannekitchens** [comment]
1. @jbaird123 actually to identify a spec it's two part: (1) organization and (2) spec.  Click the mapping team panel on this page as an example.  Some organizations have numerous specs.  Some only have one. Either way, the spec should be identified. https://credreg.net/page/T3Mapping.
2. The domains showing in the mockup were solely based on the current T3 mapping project that identified those domains.  Other domains are going to need to be included.  There may be a workflow issue as you noted but with the upload the user is going to need to identify these things shown on that screen.
3. The values have to come from the upload.   Otherwise, the admin role as to have the ability to identify them.

**Comment by stuartasutton** [comment]
I am reopening this issue. @jbaird123, please refer to https://github.com/t3-innovation-network/desm/issues/2 because it directly impacts your no. 1 question.

**Comment by richard0000** [comment]
Already Covered with PR #31
